language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements-test.txt
script:
  - pytest --cov=src --cov-branch
  - flake8 prestoplot tests
after_success:
  - coveralls
